spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/daedalus
    driverClassName: org.postgresql.Driver

liquibase:
  changelog:
    location: classpath:/database/changelog-master.xml
  schema: public

session:
  expirationSeconds: 600
  cleanup:
    intervalMillis: 60000

server:
  port: 8080

endpoint-protection:
  protectedEndpoint:
    - pathPattern: /home
      method: GET